Update credentials ci

diff --git a/.github/workflows/update-credentials.yml b/.github/workflows/update-credentials.yml
--- a/.github/workflows/update-credentials.yml
+++ b/.github/workflows/update-credentials.yml
@@ -20,8 +20,15 @@ jobs:
       - name: Fetch lastest apk information
         id: apk_info
         run: |
-          # endpoint extracted from https://github.com/vitalygashkov/crextractor
-          apk_info="$(curl -X POST -s -d 'identif=id%3A72075737&mode=json' https://webservices.aptoide.com/webservices/3/getApkInfo | jq .apk)"
+          # endpoints extracted from https://github.com/vitalygashkov/crextractor
+          apk_id="$(curl -X GET -s 'https://ws2-cache.aptoide.com/api/7/apps/search?query=crunchyroll&cdn=web&q=bXlDUFU9YXJtNjQtdjhhLGFybWVhYmktdjdhLGFybWVhYmkmbGVhbmJhY2s9MA&aab=1' | jq '.datalist.list.[0].id')"
+          
+          if [[ -z "$apk_id" ]]; then
+            echo "Failed to fetch apk id"
+            exit 1
+          fi
+          
+          apk_info="$(curl -X POST -s -d "identif=id%3A$apk_id&mode=json" https://webservices.aptoide.com/webservices/3/getApkInfo | jq .apk)"
           apk_vername=$(echo "$apk_info" | jq --raw-output .vername)
           apk_vercode=$(echo "$apk_info" | jq --raw-output .vercode)
           apk_download_path=$(echo "$apk_info" | jq --raw-output .path)
